[package]
name = "libronin_rust_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "libronin_rust.elf"
path = "src/main.rs"

[dependencies]
